"""This collects individual protein image data that has previously been generated by 'image_collect.py'"""
#__author__      = "David S. Bramer"
#__copyright__   ="2018"
import numpy as np
import pandas as pd
import sys,os
import glob

fname='/mnt/home/bramerda/Documents/Persistent_Homology/Results/'
prot_names=glob.glob('/mnt/home/bramerda/Documents/Persistent_Homology/Results/*')
prot_names.sort()
prot_names.remove(fname+'1ob4')
prot_names.remove(fname+'1ob7')
prot_names.remove(fname+'2olx')
prot_names.remove(fname+'3md5')
prot_names.remove(fname+'1nko')
prot_names.remove(fname+'2oct')
prot_names.remove(fname+'3fva')

chk=0
counter=0
rf_count=0

for i in prot_names:
  kname='/mnt/home/bramerda/Documents/Persistent_Homology/Results/'+i[-4:]+'/Image_BF.npy'
  tmp_img_bf=np.load(kname)
  tmp_RF = pd.read_pickle('/mnt/home/bramerda/Documents/Secondary_Prediction/Results/'+i[-4:]+'/Secondary_FRI_b')
  #print(list(tmp_RF))
  tmp_RF=tmp_RF[tmp_RF.Atom_Type=='CA']
  
  tmp_key = np.empty((tmp_img_bf.shape[0]),dtype='a4')
  counter=counter+tmp_img_bf.shape[0]
  rf_count=rf_count+tmp_RF.shape[0]
  tmp_key[:]=i[-4:]
  tmp_key=np.c_[tmp_key,tmp_img_bf]
  if(chk==0):
    Key=tmp_key
  else:
    Key=np.r_[Key,tmp_key]
  chk=1  

    
Image_Data = np.empty((Key.shape[0],8,10,3))
print("Staring image collection ...")
k=0    

for i in prot_names:
  sname='/mnt/home/bramerda/Documents/Persistent_Homology/Results/'+i[-4:]+'/Image.npy'
  tmp_img   =np.load(sname)
  #print(tmp_img.shape)    
  for j in range(0,tmp_img.shape[0]):
      Image_Data[k,:,:,:]  = tmp_img[j,:,:,:] 
      k = k+1

print(Image_Data.shape,Key.shape)  
np.save('/mnt/home/bramerda/Documents/Persistent_Homology/Image_Data',Image_Data,allow_pickle=True)
np.save('/mnt/home/bramerda/Documents/Persistent_Homology/Image_Key',Key,allow_pickle=True)

exit()